default:
  logging:
    debug:
      level: DEBUG
      sink: logs/file_{time:YYYY-MM-DD}.log
      format: "{time:YYYY-MM-DD HH:mm:ss}|{level}|{message}"
    info:
      level: INFO
      sink: sys.stdout
      format: "{time:YYYY-MM-DD HH:mm:ss}|{level}|{message}"
  data:
    landing:
      bvc_hist:
        path: data/landing/hist/
        ext: csv
    processed:
      bvc_hist:
        path: data/processed/hist/
        ext: csv
    raw:
      bvc_hist:
        path: data/raw/hist/data.parquet
        ext: parquet
  engine:
    steps:
      - bvc_hist
      - bvc_daily
